name: Build Result image

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . -f Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/laravelcrud

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/laravelcrud
        

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            sudo docker pull issiwara/laravelcrud
            sudo docker stop lara
            sudo docker rm lara
            
            sudo docker run -d -p 8000:8000 --name lara issiwara/ratings-data-service
            sudo docker exec lara php artisan migrate
